from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500,200)
        MainWindow.setStyleSheet("background-color: #282828")
       
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        
        self.search = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(32)
        self.search.setFont(font)
        self.search.setToolTipDuration(-3)
        self.search.setStyleSheet("background-color: #161a1e; color: white; border: 3px solid #161a1e")
        self.search.setObjectName("search")
        self.gridLayout.addWidget(self.search, 0, 0, 1, 4)
       
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(32)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: #161a1e; color: white;")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 4, 1, 1)
        
        self.line_1 = QtWidgets.QFrame(self.centralwidget)
        self.line_1.setStyleSheet("")
        self.line_1.setObjectName("line_1")
        self.line_1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.gridLayout.addWidget(self.line_1, 1, 0, 1, 5)
        
        self.marketLabel_1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.marketLabel_1.setFont(font)
        self.marketLabel_1.setStyleSheet("color: white")
        self.marketLabel_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.marketLabel_1.setFixedHeight(40)
        self.marketLabel_1.setObjectName("marketLabel_1")
        self.gridLayout.addWidget(self.marketLabel_1, 2, 0, 1, 1)
        
        self.marketLabel_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.marketLabel_2.setFont(font)
        self.marketLabel_2.setStyleSheet("color: white")
        self.marketLabel_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.marketLabel_2.setFixedHeight(40)
        self.marketLabel_2.setObjectName("marketLabel_2")
        self.gridLayout.addWidget(self.marketLabel_2, 2, 1, 1, 1)

        self.marketLabel_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.marketLabel_3.setFont(font)
        self.marketLabel_3.setStyleSheet("color: white")
        self.marketLabel_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        
        self.marketLabel_3.setFixedHeight(40)
        self.marketLabel_3.setObjectName("marketLabel_3")
        self.gridLayout.addWidget(self.marketLabel_3, 2, 2, 1, 1)
        
        self.marketLabel_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.marketLabel_4.setFont(font)
        self.marketLabel_4.setStyleSheet("color: white") 
        self.marketLabel_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.marketLabel_4.setFixedHeight(40)
        self.marketLabel_4.setObjectName("marketLabel_4")
        self.gridLayout.addWidget(self.marketLabel_4, 2, 3, 1, 1)

        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setStyleSheet("")
        self.line_2.setObjectName("line_2")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.gridLayout.addWidget(self.line_2, 3, 0, 1, 5)

        self.tradingPairs = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        self.tradingPairs.setFont(font)
        self.tradingPairs.setStyleSheet("color: white;")
        self.tradingPairs.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tradingPairs.setFixedHeight(40)
        self.tradingPairs.setObjectName("tradingPairs")
        self.gridLayout.addWidget(self.tradingPairs, 4, 0, 1, 1)
                
        self.lastTradedPrice = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        self.lastTradedPrice.setFont(font)
        self.lastTradedPrice.setStyleSheet("color: white;")
        self.lastTradedPrice.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        
        self.lastTradedPrice.setObjectName("lastTradedPrice")
        self.gridLayout.addWidget(self.lastTradedPrice, 4, 1, 1, 1)

        self.percentageChange = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        self.percentageChange.setFont(font)
        self.percentageChange.setStyleSheet("color: white;")
        self.percentageChange.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.percentageChange.setObjectName("percentageChange")
        self.gridLayout.addWidget(self.percentageChange, 4, 2, 1, 1)

        self.turnover = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        self.turnover.setFont(font)
        self.turnover.setStyleSheet("color: white;")
        self.turnover.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.turnover.setObjectName("label_5")
        self.gridLayout.addWidget(self.turnover, 4, 3, 1, 1)

        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setStyleSheet("")
        self.line_3.setObjectName("line_3")
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.gridLayout.addWidget(self.line_3, 5, 0, 1, 5)

        self.notificationsLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.notificationsLabel.setFont(font)
        self.notificationsLabel.setToolTipDuration(-3)
        self.notificationsLabel.setStyleSheet("color: white")
        self.notificationsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        # self.notificationsLabel.setFixedHeight(40)
        self.notificationsLabel.setObjectName("notificationsLabel")
        self.gridLayout.addWidget(self.notificationsLabel, 6, 0, 1, 5)

        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setStyleSheet("")
        self.line_4.setObjectName("line_5")
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.gridLayout.addWidget(self.line_4, 7, 0, 1, 5)

        self.notificationsLabel_1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.notificationsLabel_1.setFont(font)
        self.notificationsLabel_1.setToolTipDuration(-3)
        self.notificationsLabel_1.setStyleSheet("color: white")
        self.notificationsLabel_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        # self.notificationsLabel.setFixedHeight(40)
        self.notificationsLabel_1.setObjectName("notificationsLabel")
        self.gridLayout.addWidget(self.notificationsLabel_1, 8, 0, 1, 1)

        self.notificationsLabel_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.notificationsLabel_2.setFont(font)
        self.notificationsLabel_2.setToolTipDuration(-3)
        self.notificationsLabel_2.setStyleSheet("color: white")
        self.notificationsLabel_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        # self.notificationsLabel.setFixedHeight(40)
        self.notificationsLabel_2.setObjectName("notificationsLabel")
        self.gridLayout.addWidget(self.notificationsLabel_2, 8, 1, 1, 1)

        self.notificationsLabel_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.notificationsLabel_3.setFont(font)
        self.notificationsLabel_3.setToolTipDuration(-3)
        self.notificationsLabel_3.setStyleSheet("color: white")
        self.notificationsLabel_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        # self.notificationsLabel.setFixedHeight(40)
        self.notificationsLabel_3.setObjectName("notificationsLabel")
        self.gridLayout.addWidget(self.notificationsLabel_3, 8, 2, 1, 1)

        self.notificationsLabel_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.notificationsLabel_4.setFont(font)
        self.notificationsLabel_4.setToolTipDuration(-3)
        self.notificationsLabel_4.setStyleSheet("color: white")
        self.notificationsLabel_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        # self.notificationsLabel.setFixedHeight(40)
        self.notificationsLabel_4.setObjectName("notificationsLabel")
        self.gridLayout.addWidget(self.notificationsLabel_4, 8, 3, 1, 1)


        MainWindow.setCentralWidget(self.centralwidget)
    #     self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
    #     self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
    #     self.line_3.setObjectName("line_3")
    #     self.gridLayout.addWidget(self.line_3, 3, 0, 1, 4)
    #     self.line_12 = QtWidgets.QFrame(self.frame)
    #     self.line_12.setFrameShape(QtWidgets.QFrame.Shape.HLine)
    #     self.line_12.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
    #     self.line_12.setObjectName("line_12")
    #     self.gridLayout.addWidget(self.line_12, 1, 0, 1, 4)
       
    #     self.comboBox = QtWidgets.QComboBox(self.frame)
    #     sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
    #     sizePolicy.setHorizontalStretch(0)
    #     sizePolicy.setVerticalStretch(0)
    #     sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
    #     self.comboBox.setSizePolicy(sizePolicy)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(20)
    #     self.comboBox.setFont(font)
    #     self.comboBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
    #     self.comboBox.setAutoFillBackground(False)
    #     self.comboBox.setStyleSheet("border: 0")
    #     self.comboBox.setObjectName("comboBox")
    #     self.comboBox.addItem("")
    #     self.comboBox.addItem("")
    #     self.comboBox.addItem("")
    #     self.comboBox.addItem("")
    #     self.comboBox.addItem("")
    #     self.gridLayout.addWidget(self.comboBox, 0, 4, 1, 1)
    #     self.label_5 = QtWidgets.QLabel(self.frame)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(20)
    #     self.label_5.setFont(font)
    #     self.label_5.setStyleSheet("border: 1px")
    #     self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
    #     self.label_5.setObjectName("label_5")
    #     self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
    #     self.label_4 = QtWidgets.QLabel(self.frame)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(20)
    #     self.label_4.setFont(font)
    #     self.label_4.setStyleSheet("border: 1px")
    #     self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
    #     self.label_4.setObjectName("label_4")
    #     self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
    #     self.label_3 = QtWidgets.QLabel(self.frame)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(20)
    #     self.label_3.setFont(font)
    #     self.label_3.setStyleSheet("border: 1px")
    #     self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
    #     self.label_3.setObjectName("label_3")
    #     self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
    #     self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
    #     self.lineEdit_3.setEnabled(True)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(24)
    #     self.lineEdit_3.setFont(font)
    #     self.lineEdit_3.setStyleSheet("border: 0")
    #     self.lineEdit_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
    #     self.lineEdit_3.setObjectName("lineEdit_3")
    #     self.gridLayout.addWidget(self.lineEdit_3, 2, 0, 1, 1)
       
        
    #     self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
    #     self.lineEdit_2.setEnabled(True)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(24)
    #     self.lineEdit_2.setFont(font)
    #     self.lineEdit_2.setStyleSheet("border: 0")
    #     self.lineEdit_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
    #     self.lineEdit_2.setObjectName("lineEdit_2")
    #     self.gridLayout.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        
    #     self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
    #     self.lineEdit_4.setEnabled(True)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(24)
    #     self.lineEdit_4.setFont(font)
    #     self.lineEdit_4.setStyleSheet("border: 0")
    #     self.lineEdit_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
    #     self.lineEdit_4.setObjectName("lineEdit_4")
    #     self.gridLayout.addWidget(self.lineEdit_4, 2, 2, 1, 1)
    #     self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
    #     self.lineEdit_5.setEnabled(True)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(24)
    #     self.lineEdit_5.setFont(font)
    #     self.lineEdit_5.setStyleSheet("border: 0")
    #     self.lineEdit_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
    #     self.lineEdit_5.setObjectName("lineEdit_5")
    #     self.gridLayout.addWidget(self.lineEdit_5, 2, 3, 1, 1)
       
        
    #     self.label_2 = QtWidgets.QLabel(self.frame)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(20)
    #     self.label_2.setFont(font)
    #     self.label_2.setStyleSheet("border: 1px")
    #     self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
    #     self.label_2.setObjectName("label_2")
    #     self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
    #     self.verticalLayout.addWidget(self.frame)
    #     self.frame_3 = QtWidgets.QFrame(self.centralwidget)
    #     sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
    #     sizePolicy.setHorizontalStretch(0)
    #     sizePolicy.setVerticalStretch(0)
    #     sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
    #     self.frame_3.setSizePolicy(sizePolicy)
    #     self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
    #     self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
    #     self.frame_3.setObjectName("frame_3")
    #     self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
    #     self.gridLayout_3.setObjectName("gridLayout_3")
    #     self.lineEdit_28 = QtWidgets.QLineEdit(self.frame_3)
    #     self.lineEdit_28.setEnabled(True)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(24)
    #     self.lineEdit_28.setFont(font)
    #     self.lineEdit_28.setStyleSheet("border: 0")
    #     self.lineEdit_28.setObjectName("lineEdit_28")
    #     self.gridLayout_3.addWidget(self.lineEdit_28, 6, 3, 1, 1)
    #     self.lineEdit_30 = QtWidgets.QLineEdit(self.frame_3)
    #     self.lineEdit_30.setEnabled(True)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(24)
    #     self.lineEdit_30.setFont(font)
    #     self.lineEdit_30.setStyleSheet("border: 0")
    #     self.lineEdit_30.setObjectName("lineEdit_30")
    #     self.gridLayout_3.addWidget(self.lineEdit_30, 6, 1, 1, 1)
    #     self.lineEdit_23 = QtWidgets.QLineEdit(self.frame_3)
    #     self.lineEdit_23.setEnabled(True)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(24)
    #     self.lineEdit_23.setFont(font)
    #     self.lineEdit_23.setStyleSheet("border: 0")
    #     self.lineEdit_23.setObjectName("lineEdit_23")
    #     self.gridLayout_3.addWidget(self.lineEdit_23, 4, 3, 1, 1)
    #     self.lineEdit_24 = QtWidgets.QLineEdit(self.frame_3)
    #     self.lineEdit_24.setEnabled(True)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(24)
    #     self.lineEdit_24.setFont(font)
    #     self.lineEdit_24.setStyleSheet("border: 0")
    #     self.lineEdit_24.setObjectName("lineEdit_24")
    #     self.gridLayout_3.addWidget(self.lineEdit_24, 4, 4, 1, 1)
    #     self.lineEdit_22 = QtWidgets.QLineEdit(self.frame_3)
    #     self.lineEdit_22.setEnabled(True)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(24)
    #     self.lineEdit_22.setFont(font)
    #     self.lineEdit_22.setStyleSheet("border: 0")
    #     self.lineEdit_22.setObjectName("lineEdit_22")
    #     self.gridLayout_3.addWidget(self.lineEdit_22, 6, 4, 1, 1)
    #     self.lineEdit_32 = QtWidgets.QLineEdit(self.frame_3)
    #     self.lineEdit_32.setEnabled(True)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(24)
    #     self.lineEdit_32.setFont(font)
    #     self.lineEdit_32.setStyleSheet("border: 0")
    #     self.lineEdit_32.setObjectName("lineEdit_32")
    #     self.gridLayout_3.addWidget(self.lineEdit_32, 4, 2, 1, 1)
    #     self.lineEdit_34 = QtWidgets.QLineEdit(self.frame_3)
    #     self.lineEdit_34.setEnabled(True)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(24)
    #     self.lineEdit_34.setFont(font)
    #     self.lineEdit_34.setStyleSheet("border: 0")
    #     self.lineEdit_34.setObjectName("lineEdit_34")
    #     self.gridLayout_3.addWidget(self.lineEdit_34, 6, 2, 1, 1)
    #     self.lineEdit_25 = QtWidgets.QLineEdit(self.frame_3)
    #     self.lineEdit_25.setEnabled(True)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(24)
    #     self.lineEdit_25.setFont(font)
    #     self.lineEdit_25.setStyleSheet("border: 0")
    #     self.lineEdit_25.setObjectName("lineEdit_25")
    #     self.gridLayout_3.addWidget(self.lineEdit_25, 4, 1, 1, 1)
    #     self.label_7 = QtWidgets.QLabel(self.frame_3)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(20)
    #     self.label_7.setFont(font)
    #     self.label_7.setStyleSheet("border: ")
    #     self.label_7.setObjectName("label_7")
    #     self.gridLayout_3.addWidget(self.label_7, 2, 1, 1, 1)
    #     self.label_9 = QtWidgets.QLabel(self.frame_3)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(20)
    #     self.label_9.setFont(font)
    #     self.label_9.setStyleSheet("border: ")
    #     self.label_9.setObjectName("label_9")
    #     self.gridLayout_3.addWidget(self.label_9, 2, 3, 1, 1)
    #     self.label_10 = QtWidgets.QLabel(self.frame_3)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(20)
    #     self.label_10.setFont(font)
    #     self.label_10.setStyleSheet("border: ")
    #     self.label_10.setObjectName("label_10")
    #     self.gridLayout_3.addWidget(self.label_10, 2, 4, 1, 1)
    #     self.label_8 = QtWidgets.QLabel(self.frame_3)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(20)
    #     self.label_8.setFont(font)
    #     self.label_8.setStyleSheet("border: ")
    #     self.label_8.setObjectName("label_8")
    #     self.gridLayout_3.addWidget(self.label_8, 2, 2, 1, 1)
    #     self.label_6 = QtWidgets.QLabel(self.frame_3)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(24)
    #     self.label_6.setFont(font)
    #     self.label_6.setStyleSheet("border: ")
    #     self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
    #     self.label_6.setObjectName("label_6")
    #     self.gridLayout_3.addWidget(self.label_6, 0, 4, 1, 1)
    #     self.lineEdit_29 = QtWidgets.QLineEdit(self.frame_3)
    #     self.lineEdit_29.setEnabled(True)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(24)
    #     self.lineEdit_29.setFont(font)
    #     self.lineEdit_29.setStyleSheet("border: 0")
    #     self.lineEdit_29.setObjectName("lineEdit_29")
    #     self.gridLayout_3.addWidget(self.lineEdit_29, 8, 1, 1, 1)
    #     self.lineEdit_35 = QtWidgets.QLineEdit(self.frame_3)
    #     self.lineEdit_35.setEnabled(True)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(24)
    #     self.lineEdit_35.setFont(font)
    #     self.lineEdit_35.setStyleSheet("border: 0")
    #     self.lineEdit_35.setObjectName("lineEdit_35")
    #     self.gridLayout_3.addWidget(self.lineEdit_35, 8, 2, 1, 1)
    #     self.lineEdit_36 = QtWidgets.QLineEdit(self.frame_3)
    #     self.lineEdit_36.setEnabled(True)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(24)
    #     self.lineEdit_36.setFont(font)
    #     self.lineEdit_36.setStyleSheet("border: 0")
    #     self.lineEdit_36.setObjectName("lineEdit_36")
    #     self.gridLayout_3.addWidget(self.lineEdit_36, 8, 3, 1, 1)
    #     self.lineEdit_37 = QtWidgets.QLineEdit(self.frame_3)
    #     self.lineEdit_37.setEnabled(True)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(24)
    #     self.lineEdit_37.setFont(font)
    #     self.lineEdit_37.setStyleSheet("border: 0")
    #     self.lineEdit_37.setObjectName("lineEdit_37")
    #     self.gridLayout_3.addWidget(self.lineEdit_37, 10, 4, 1, 1)
    #     self.lineEdit_31 = QtWidgets.QLineEdit(self.frame_3)
    #     self.lineEdit_31.setEnabled(True)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(24)
    #     self.lineEdit_31.setFont(font)
    #     self.lineEdit_31.setStyleSheet("border: 0")
    #     self.lineEdit_31.setObjectName("lineEdit_31")
    #     self.gridLayout_3.addWidget(self.lineEdit_31, 8, 4, 1, 1)
    #     self.lineEdit_26 = QtWidgets.QLineEdit(self.frame_3)
    #     self.lineEdit_26.setEnabled(True)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(24)
    #     self.lineEdit_26.setFont(font)
    #     self.lineEdit_26.setStyleSheet("border: 0")
    #     self.lineEdit_26.setObjectName("lineEdit_26")
    #     self.gridLayout_3.addWidget(self.lineEdit_26, 10, 3, 1, 1)
    #     self.lineEdit_33 = QtWidgets.QLineEdit(self.frame_3)
    #     self.lineEdit_33.setEnabled(True)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(24)
    #     self.lineEdit_33.setFont(font)
    #     self.lineEdit_33.setStyleSheet("border: 0")
    #     self.lineEdit_33.setObjectName("lineEdit_33")
    #     self.gridLayout_3.addWidget(self.lineEdit_33, 10, 2, 1, 1)
    #     self.lineEdit_27 = QtWidgets.QLineEdit(self.frame_3)
    #     self.lineEdit_27.setEnabled(True)
    #     font = QtGui.QFont()
    #     font.setFamily("Times New Roman")
    #     font.setPointSize(24)
    #     self.lineEdit_27.setFont(font)
    #     self.lineEdit_27.setStyleSheet("border: 0")
    #     self.lineEdit_27.setObjectName("lineEdit_27")
    #     self.gridLayout_3.addWidget(self.lineEdit_27, 10, 1, 1, 1)
    #     self.frame_2 = QtWidgets.QFrame(self.frame_3)
    #     sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
    #     sizePolicy.setHorizontalStretch(0)
    #     sizePolicy.setVerticalStretch(0)
    #     sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
    #     self.frame_2.setSizePolicy(sizePolicy)
    #     self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
    #     self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
    #     self.frame_2.setObjectName("frame_2")
    #     self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
    #     self.gridLayout_2.setObjectName("gridLayout_2")
    #     self.line_14 = QtWidgets.QFrame(self.frame_2)
    #     self.line_14.setFrameShape(QtWidgets.QFrame.Shape.HLine)
    #     self.line_14.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
    #     self.line_14.setObjectName("line_14")
    #     self.gridLayout_2.addWidget(self.line_14, 13, 1, 1, 4)
    #     self.gridLayout_3.addWidget(self.frame_2, 1, 0, 1, 5)
    #     self.line_10 = QtWidgets.QFrame(self.frame_3)
    #     self.line_10.setFrameShape(QtWidgets.QFrame.Shape.HLine)
    #     self.line_10.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
    #     self.line_10.setObjectName("line_10")
    #     self.gridLayout_3.addWidget(self.line_10, 3, 0, 1, 5)
    #     self.line_2 = QtWidgets.QFrame(self.frame_3)
    #     self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
    #     self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
    #     self.line_2.setObjectName("line_2")
    #     self.gridLayout_3.addWidget(self.line_2, 5, 0, 1, 5)
    #     self.line_13 = QtWidgets.QFrame(self.frame_3)
    #     self.line_13.setFrameShape(QtWidgets.QFrame.Shape.HLine)
    #     self.line_13.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
    #     self.line_13.setObjectName("line_13")
    #     self.gridLayout_3.addWidget(self.line_13, 7, 0, 1, 5)
    #     self.line_9 = QtWidgets.QFrame(self.frame_3)
    #     self.line_9.setFrameShape(QtWidgets.QFrame.Shape.HLine)
    #     self.line_9.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
    #     self.line_9.setObjectName("line_9")
    #     self.gridLayout_3.addWidget(self.line_9, 9, 0, 1, 5)
    #     self.line_11 = QtWidgets.QFrame(self.frame_3)
    #     self.line_11.setFrameShape(QtWidgets.QFrame.Shape.HLine)
    #     self.line_11.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
    #     self.line_11.setObjectName("line_11")
    #     self.gridLayout_3.addWidget(self.line_11, 11, 0, 1, 5)
    #     self.verticalLayout.addWidget(self.frame_3)
    #     MainWindow.setCentralWidget(self.centralwidget)
    #     self.menubar = QtWidgets.QMenuBar(MainWindow)
    #     self.menubar.setGeometry(QtCore.QRect(0, 0, 1344, 21))
    #     self.menubar.setObjectName("menubar")
    #     MainWindow.setMenuBar(self.menubar)
    #     self.statusbar = QtWidgets.QStatusBar(MainWindow)
    #     self.statusbar.setObjectName("statusbar")
    #     MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "найти"))
    #     self.comboBox.setItemText(0, _translate("MainWindow", "добавить фильтр"))
    #     self.comboBox.setItemText(1, _translate("MainWindow", "Изменения, 1м, %"))
    #     self.comboBox.setItemText(2, _translate("MainWindow", "Изменения, 3м, %"))
    #     self.comboBox.setItemText(3, _translate("MainWindow", "Изменения, 15м, %"))
    #     self.comboBox.setItemText(4, _translate("MainWindow", "Изменения, 24ч, %"))
        self.marketLabel_1.setText(_translate("MainWindow", "Торговая пара"))
        self.marketLabel_2.setText(_translate("MainWindow", "Цена"))
        self.marketLabel_3.setText(_translate("MainWindow", "Изменения, %"))
        self.marketLabel_4.setText(_translate("MainWindow", "Объемы"))
        self.notificationsLabel.setText(_translate("MainWindow", "Уведомления"))
        self.notificationsLabel_1.setText(_translate("MainWindow", "Торговая пара"))
        self.notificationsLabel_2.setText(_translate("MainWindow", "Цена"))
        self.notificationsLabel_3.setText(_translate("MainWindow", "Изменения, %"))
        self.notificationsLabel_4.setText(_translate("MainWindow", "Дата и время"))
    #     self.label_7.setText(_translate("MainWindow", "Торговая пара"))
    #     self.label_9.setText(_translate("MainWindow", "Изменения"))
    #     self.label_10.setText(_translate("MainWindow", "Дата"))
    #     self.label_8.setText(_translate("MainWindow", "Цена"))
    #     self.label_6.setText(_translate("MainWindow", "Уведомления"))
       
        
       

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())